name: Ignore path

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    if: github.event_name == 'pull_request'
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World!"
