name: Ignore path

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World!"
